### ISSUE TITLE
Invite for [SWE INTERN]

### ISSUE THREAD

**Issue by wiptrax** [safedep-hiring/swe-intern-problem-1#1]
hello [@abhisek](https://github.com/abhisek) Sir,
I have sent you an invite link to my forked repo. So that you could be the reviewer of my requested as suggest in readme file please accept my invitation.

[invite link ](https://github.com/wiptrax/swe-intern-problem-1/invitations)

**Comment by CHIRANTH-24** [comment]
@wiptrax and @abhisek 
Is this position still open?

**Comment by abhisek** [comment]
@CHIRANTH-24 Refer to https://safedep-inc.notion.site/Software-Engineering-Intern-f61df3d2dd5f44ecab0f8232fee6b756
